version: "3.9"

services:

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB={{cookiecutter.project_slug}}
      - POSTGRES_USER={{cookiecutter.postgres_user}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:alpine"
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  pgadmin:
    container_name: pgadmin4_{{cookiecutter.project_slug}}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: {{cookiecutter.pgadmin_user}}
      PGADMIN_DEFAULT_PASSWORD: "{{cookiecutter.pgadmin_password}}" 
    ports:
      - "5050:80"

volumes:
    postgres-data:
    redis-data:

